### PR TITLE
Fix operator handling

### LINKED ISSUE #7: Add support for missing operators
See: #167, #150, #135, 

**List of missing ops:**
Postgres: (#126)
- ||
- :=
- =>

Unspecified/Multiple:
- =>
- !=

### LINKED ISSUE #8: Add support for adjacent unary operators
Adjacent parts of a token often get clipped or spaced when they should be included with its dependent token (See: #123, #173, #166)

### PR DESCRIPTION
**Pull request by inferrinizzard**
Fixes the following issues:
- #7
- zeroturnaround#150
- zeroturnaround#167
- zeroturnaround#135
- zeroturnaround#125
- zeroturnaround#176
- zeroturnaround#139
- zeroturnaround#155
- #8 
- zeroturnaround#123
- zeroturnaround#166
- zeroturnaround#162
- zeroturnaround#137

Changes:
- added proper backtick handling for standard SQL
- updated operator lists for all languages
- added exhaustive list of monad operators to regexFactory/Tokenizer
- added support for curly braces ({})
- added test for curly braces and backticks
- (util) updated isToken function
- added hex string type for Pl/SQL (x'')
- added negative lookahead for reserved words to prevent matching on words with specialWordChars
- broke specialWordChar into 3 categories of prefix(only start), suffix(only tail), any(where)
  - added : as prefix for MySQL
- added @@ support for MySQL system variables
- added support for array accessors (column[1]) and map accessors (column['key'])

### CODE REVIEW

File: src/languages/Db2Formatter.ts [hunk 1]
```diff
@@ -866,14 +866,14 @@ export default class Db2Formatter extends Formatter {
...
-	static stringTypes: StringPatternType[] = [`""`, "''", '``', '[]'];
+	static stringTypes: StringPatternType[] = [`""`, "''", '``', '[]', "x''"];
 	static blockStart = ['('];
 	static blockEnd = [')'];
 	static indexedPlaceholderTypes = ['?'];
 	static namedPlaceholderTypes = [':'];
 	static lineCommentTypes = ['--'];
-	static specialWordChars = ['#', '@'];
-	static operators = ['**', '!=', '!>', '!>', '||'];
+	static specialWordChars = { any: '#@' };
```
Comment (inferrinizzard) [inline src/languages/Db2Formatter.ts:875]: is the # char no longer needed ?

File: src/languages/PlSqlFormatter.ts [hunk 2]
```diff
@@ -473,11 +483,19 @@ export default class PlSqlFormatter extends Formatter {
 	}
 
 	tokenOverride(token: Token) {
-		if (isToken('SET')(token) && isToken('BY')(this.previousReservedToken)) {
+		if (
+			token.value === '.' &&
+			this.tokenLookAhead()?.value.startsWith('`') &&
```
Comment (inferrinizzard) [inline src/languages/PlSqlFormatter.ts:488]: add comments here

**Review by inferrinizzard — COMMENTED** [review]
- Update string type regexes later
- double check operator lists in future
