### PR TITLE
Fix inferrinizzard#37, handle CLI with no args

### LINKED ISSUE #37: CLI tool throws error message when run with no args
```sh
$ npx prettier-sql
npx: installed 2 in 1.681s
Cannot read property '1' of undefined
```

Need to print usage + improve CLI tool

### PR DESCRIPTION
**Pull request by inferrinizzard**
- now prints help and exits CLI when no args are passed
- CLI functions grouped together in class

### CODE REVIEW

File: bin/prettier-sql-cli.js [hunk 1]
```diff
@@ -0,0 +1,109 @@
+#!/usr/bin/env node
+
+'use strict';
+
+const { format, supportedDialects } = require('../lib/sqlFormatter');
```
Comment (inferrinizzard) [inline bin/prettier-sql-cli.js]: update this to index, as of #39
